require("plugins.completion")
require("plugins.navigation")
require("plugins.mini")
require("plugins.mason")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.ui")
require("plugins.which-key")
